name: Daily Commit

on:
  schedule:
    - cron: '34 10 * * *'  # 18:41 IST
  workflow_dispatch:
permissions:
  contents: write
jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main  # 👈 explicitly use the main branch

      - name: Configure Git - 22f3000162@ds.study.iitm.ac.in
        run: |
          git config user.name "auto-commit"
          git config user.email "22f3000162@ds.study.iitm.ac.in"

      - name: Make a dummy commit
        run: |
          # echo "Run at $(date -u +'%Y-%m-%dT%H:%M:%SZ')" > daily-log.txt
          # git add daily-log.txt
          # git commit -m "Daily commit at $(date -u)" || echo "Nothing to commit"
          # git push origin main
